dist: xenial
python:
    - "3.6"
install:
    # install latest release versi
    - wget https://github.com/gohugoio/hugo/releases/download/v0.51/hugo_0.51_Linux-64bit.deb
    - sudo apt install ./hugo_0.51_Linux-64bit.deb
    - sudo pip install Pygments
    - rm -rf public 2> /dev/null

script:
    - hugo
    - echo 'vmcworkshop.com' > public/CNAME

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN  # Set in travis-ci.org dashboard, marked secure
  email: $GH_EMAIL
  name: $GH_NAME
  verbose: true
  keep-history: true
  local-dir: public
  target_branch: gh-pages  # branch contains blog content
  on:
    branch: master  # branch contains Hugo generator code