languageCode = "en-us"
defaultContentLanguage = "en"
title = "VMC Workshop"
theme = "learn"
uglyurls = false
googleAnalytics = ""
sectionPagesMenu = "main"
relativeURLs = true

[blackfriday]
hrefTargetBlank = true

[params]
editURL = "https://github.com/vmcworkshop/vmcworkshop/blob/master/content/"
themeVariant = "mine"
showVisitedLinks = false
author = "VMC Workshop Team"
description = "VMC Workshop"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle=false
disableInlineCopyToClipBoard = true
ghrepo = "https://github.com/vmcworkshop/vmcworkshop/"
branch = "master"
template_bucket = ""

#

[menu]
  [[menu.main]]
    identifier = "Prerequisites"
    name = "This is the Mu track"
    title = "Workshop using Mu"
    url = "/mu/"
    weight = -110

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> More Resources"
url = "/more_resources"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-users'></i> Authors"
url = "/authors"
weight = 20

[[menu.shortcuts]]
name = "<i class='fab fa-github'></i> GitHub Project"
url = "https://github.com/vmcworkshop/vmcworkshop/"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-envelope'></i> Have questions?"
url = "mailto:unicornranch@amazon.com"
weight = 40


[outputs]
home = [ "HTML", "JSON"]
page = [ "HTML" ]
